# shared configurations between development & production
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: 192.168.1.51:8083/node-app
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
